WIP adding credential support for inprocess nuget client (please don't merge)
cake-build/cake pull request #2090
Opened 2018-03-17 09:16 UTC by Insire

added NuGet.Credentials package,
added WIP call to PluginCredentialProviderBuilder

2018-06-20 09:36 UTC, devlead requested changes
@Insire there's a conflict with this PR and develop that needs to be resolved before this PR can be reviewed.

2018-07-02 22:57 UTC, axdiamond commented
@Insire do you intend to finish this PR?

2018-07-03 08:12 UTC, Insire commented
RL is rather busy for me at the moment, so if anyone wants to take over, go ahead.

2019-03-21 04:11 UTC, mholo65 commented
@Insire I'll take over at some point. Talked to NuGet team today, and we should dig into the plugin system for authentication.

2019-03-21 07:24 UTC, Insire commented
Sounds good.

2022-05-15 20:39 UTC, gep13 commented
@bjorkstromm can you elaborate on this comment:

> Talked to NuGet team today, and we should dig into the plugin system for authentication.

Is there something specific that we should be looking at here?  If so, can you point us in the right direction?  Or perhaps update the original issue with your thoughts on this?

Is this something that should be left to say the "NuGet Authenticate" task in Azure DevOps (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) rather than something that should be brought into Cake?

2025-05-01 17:05 UTC, CRuppert commented
I've started to run into this issue with a recipe being hosted in codeartifact.
As in this doesn't seem to work with the codeartifact credential provider.

2025-12-06 17:28 UTC, closed without merging

2025-12-06 17:28 UTC, gep13 commented
@Insire a new [PR](https://github.com/cake-build/cake/pull/4473) has been raised, which is attempting to address the issue in #2028.

As such, I am going to go ahead and close out this issue.

Please let me know if you have any concerns about this.