GH-2755: Add DirectoryHashCalculator
cake-build/cake pull request #2829
Opened 2020-07-10 12:10 UTC by eoehen

- Add DirectoryHash represents a calculated directory hash.
- Add DirectoryHashCalculator for calculating a hash for a directory.
- Add HashAlgorithmBuilder for a common usage of creating a instance of the hash algorithm.

- Overload the ctor of FileHashCalculator with IHashAlgorithmBuilder as additional parameter.

2020-07-10 12:10 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=2829) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=2829) before we can accept your contribution.<br/><br/>:x: eoehen [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=2829)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=2829) it.</sub>

2020-09-07 11:55 UTC, devlead requested changes

2020-09-07 11:55 UTC, devlead commented on src/Cake.Common/Security/HashAlgorithmBuilder.cs
> +        public System.Security.Cryptography.HashAlgorithm GetHashAlgorithm(HashAlgorithm hashAlgorithm)
```suggestion
        public System.Security.Cryptography.HashAlgorithm CreateHashAlgorithm(HashAlgorithm hashAlgorithm)
```
If this goes public I'll suggest we call it `Create`.

2020-09-07 17:10 UTC, eoehen commented
@devlead I have processed your feedback.

2020-09-08 05:51 UTC, devlead approved these changes
LGTM 👍

2020-09-08 05:52 UTC, merged

2020-09-08 05:52 UTC, devlead commented
@eoehen your changes have been merged, thanks for your contribution 👍