Add implicit bootstrapping of modules
cake-build/cake pull request #2849
Opened 2020-09-08 21:56 UTC by patriksvensson

Closes #2833

2020-09-09 08:53 UTC, devlead requested changes
`.\tools\dotnet-cake.exe ./build.cake --bootstrap` should not execute script.

2020-09-09 11:49 UTC, patriksvensson commented
@cake-build/cake-team Ready for review

2020-09-09 13:47 UTC, devlead approved these changes
I've taken this for a spin, afaik as I can see it works as intended i.e.
```PowerShell
Test-Path .\tools\modules
.\tools\dotnet-cake.exe --target=Clean
Test-Path .\tools\modules
```
outputs
```
False
Tool GitVersion.Tool is already installed, with required version.
Tool SignClient is already installed, with required version.
Tool GitReleaseManager.Tool is already installed, with required version.

----------------------------------------
Setup
----------------------------------------
Calculating Semantic Version
Calculated Semantic Version: 1.0.0-GH-2833-0001
Building version 1.0.0-GH-2833-0001 of Cake (Release, Clean) using version 1.0.0.0 of Cake. (IsTagged: False)

========================================
Clean
========================================

----------------------------------------
Teardown
----------------------------------------
Starting Teardown...
Finished running tasks.

Task                          Duration
--------------------------------------------------
Setup                         00:00:01.0869588
Clean                         00:00:00.1628303
Teardown                      00:00:00.0054472
--------------------------------------------------
Total:                        00:00:01.2552363
True
```

First `False` in output = no module folder
Last `True` in output + that it starts = modules fetched and script executed

And running
```PowerShell
Test-Path .\tools\modules
.\tools\dotnet-cake.exe build.cake --bootstrap
Test-Path .\tools\modules
```
outputs 
```
False
True
```
First `False` in output = no module folder
Last `True` in output + nothing else= modules fetched but script not executed

2020-09-14 20:43 UTC, merged

2020-09-14 20:43 UTC, devlead commented
@patriksvensson your changes have been merged, thanks for your contribution 👍