GH2838: MakeRelative alias
cake-build/cake pull request #2923
Opened 2020-10-29 20:30 UTC by daveMueller

closes #2838

2020-10-29 23:21 UTC, patriksvensson requested changes
LGTM! Just two minor things that need to be fixed

2020-10-29 23:21 UTC, patriksvensson commented on src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
> +                // When
Line break

2020-10-29 23:21 UTC, patriksvensson commented on src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
> +                // When
Line break

2020-10-31 20:28 UTC, daveMueller commented on src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
> +                // When
Done

2020-10-31 20:28 UTC, daveMueller commented on src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
> +                // When
Done

2020-12-09 12:45 UTC, devlead approved these changes
LGTM 👍

2020-12-09 13:07 UTC, merged

2020-12-09 13:07 UTC, devlead commented
@daveMueller your changes have been merged, thanks for your contribution 👍