Add Additional Information to TeamCityBuildInfo
cake-build/cake pull request #3113
Opened 2021-02-10 11:30 UTC by BlythMeister

Adding support in the `TeamCityBuildInfo` to load the properties XML files as a key/value data store.
Files loaded as a Lazy to prevent IO when properties are not required & to also then cache the results if subsequent queries are to properties are required.

Also exposing the teamcity branch name.

NOTE: no test of loading the XML files have been added as i am unsure about the rules/convention for this sort of test for cake.

2021-02-10 11:31 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3113) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3113) before we can accept your contribution.<br/><br/>:x: BlythMeister [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3113)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=3113) it.</sub>

2021-02-10 11:31 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3113) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3113) before we can accept your contribution.<br/><br/>:x: BlythMeister [sign now](https://cla.dotnetfoundation.org/cake-build/cake?pullRequest=3113)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/cake?pullRequest=3113) it.</sub>

2021-02-10 12:30 UTC, devlead requested changes
> NOTE: no test of loading the XML files have been added as i am unsure about the rules/convention for this sort of test for cake.

Usually, we add sample XML to resources so we can test functionality works on known good data and keep that working overtime.

One example you can look at is XML peek tests

Resources
https://github.com/cake-build/cake/blob/ec61403f1c4ab9594c38f1c71662a9cc17432f79/src/Cake.Common.Tests/Properties/Resources.Designer.cs#L771-L775

https://github.com/cake-build/cake/blob/ec61403f1c4ab9594c38f1c71662a9cc17432f79/src/Cake.Common.Tests/Properties/Resources.resx#L1033-L1047

How it can be accessed/used in tests.
https://github.com/cake-build/cake/blob/8bc15841e97944291946a89f335562244965247e/src/Cake.Common.Tests/Unit/XML/XmlPeekAliasesTests.cs#L111-L124

2021-02-10 14:08 UTC, BlythMeister commented
Perfect, I shall add a test with some sample data.

Thanks for the quick review

2021-02-11 10:13 UTC, BlythMeister commented
@devlead I have added tests now.

This did require me to update some other bits and other tests to support passing the IFileSystem through.
Other good news...the tests showed an issue with my XPath :D

2021-02-13 17:57 UTC, devlead commented
@BlythMeister starting to look good to me 👍 

There's a few merge conflicts because older PRs merged, could you please rebase against latest develop branch and take a look at addressing them?

Also is there an issue related to this PR? If not could you please add one? Normally we require issues before PR for buying, but we also use them for release notes and blog post generations.

2021-02-13 18:07 UTC, BlythMeister commented
Ahh sure.

I'll rebase on monday and will raise an issue and tag it to this pr in the description 👍

2021-02-13 18:18 UTC, BlythMeister commented
Turns out someone had raised an issue...I now raised a duplicate :facepalm:

2021-02-13 18:51 UTC, augustoproiete commented
@BlythMeister @devlead PR LGTM, but wanted to run something by you before it's too late to make changes (if any needed) to the `TeamCityBuildInfo` public API:

TeamCity currently generates 6 (six) files per build, 3 (three) different pairs / sets or properties (`.properties` and `.properties.xml` equivalent):

#### 1. TeamCity configuration parameters for build
- `teamcity.build(...).properties` and `teamcity.build(...).properties.xml`

#### 2. TeamCity build properties without 'system.' prefix
- `teamcity.config(...).properties` and `teamcity.config(...).properties.xml`

#### 3. TeamCity build runner parameters
- `teamcity.runner(...).properties` and `teamcity.runner(...).properties.xml`

This PR is implementing number (1) above and exposing the values `TeamCity.Build.Properties`, which is fine.

However, once we implement items (2) and (3), how should we make these properties available?

One option could be completely separate properties, e.g. `TeamCity.Config.Properties` and `TeamCity.Runner.Properties` in which case doesn't affect this PR.

Another option would be to merge all three files into `TeamCity.Build.Properties` but there are duplicate properties across the files, so we'd need to decide how to handle those.

One other option, would be to rename the property in this PR to be something more specific to the file it reads from e.g. `TeamCity.Build.BuildProperties`, and later use `TeamCity.Build.ConfigProperties` and `TeamCity.Build.RunnerProperties` for consistency.

What do you think?

2021-02-13 18:56 UTC, BlythMeister commented
I think renaming the properties makes good sense.

I would be happy to include the other files in this PR aswell if you think it would be useful?

I am already reading file 2 in order to find the path for file 1, so adding file 3 in and exposing file 2 rather than discarding it is pretty trivial and can implement them all with lazy, so files only read when needed.

I'm not working until Monday, but will sort conflicts and and the last file in then 👍

2021-02-13 19:10 UTC, augustoproiete commented
Sounds great @BlythMeister. I didn't want to augment the scope of your PR, but since you're offering I'll take it :smile:

In terms of the API, I'm fine with 3 separate dictionaries with different names, but let's see if we can get a few more eyes on this PR from the @cake-build/cake-team in case they have other ideas

2021-02-13 19:16 UTC, BlythMeister commented
As a 1st pr and my 1st use of cake.  So far the community have been great.  I'm more than happy to give back where I can 🙂

2021-02-15 10:39 UTC, BlythMeister commented
@augustoproiete @devlead I have rebased this on develop & resolved the conflicts.
I have also now included all 3 of the properties files as part of the BuildInfo

2021-02-17 04:18 UTC, augustoproiete commented
End-to-end test results running on TeamCity 2020.2.2:

| | Feature | Comments |
|:---:| --- | --- |
| :white_check_mark: | `TeamCity.Environment.Build.BranchName` | Branch name read from TeamCity as expected |
| :white_check_mark: | `TeamCity.Environment.Build.VcsBranchName` |  VCS branch name read from TeamCity as expected |
| :white_check_mark: | Properties from `teamcity.build.properties.xml` | All build properties read from TeamCity as expected |
| :white_check_mark: | Properties from `teamcity.config.properties.xml` | All config properties from TeamCity as expected |
| :white_check_mark: | Properties from `teamcity.runner.properties.xml` | All runner properties from TeamCity as expected |

---

### TeamCity generated files

- `teamcity.build.properties.xml` (_content sampled_)

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>TeamCity build properties without 'system.' prefix</comment>
<entry key="agent.home.dir">D:\TeamCity\buildAgent01</entry>
<entry key="agent.name">AUGUSTO-TC-01</entry>
<entry key="teamcity.version">2020.2.2 (build 85899)</entry>
</properties>
```

-`teamcity.config.properties.xml` (_content sampled_)

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>TeamCity configuration parameters for build with id 214913</comment>
<entry key="build.triggeredBy">C. Augusto Proiete</entry>
<entry key="build.triggeredBy.username">augustoproiete</entry>
<entry key="DotNetCLI_Path">C:\Program Files\dotnet\dotnet.exe</entry>
</properties>
```

- `teamcity.runner.properties.xml` (_content sampled_)

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>TeamCity build runner parameters</comment>
<entry key="teamcity.build.checkoutDir">D:\agent01\w\ad0d02f87a570f9d</entry>
<entry key="teamcity.fail.exit.code">true</entry>
<entry key="teamcity.step.mode">default</entry>
<entry key="use.custom.script">true</entry>
</properties>
```

### Test script

- `teamcity.cake`

```csharp
Information("TeamCity.Environment.Build.BranchName: {0}", TeamCity.Environment.Build.BranchName);
Information("TeamCity.Environment.Build.VcsBranchName: {0}", TeamCity.Environment.Build.VcsBranchName);

Information("");
Information("---");
Information("");

Information("TeamCity.Environment.Build.BuildProperties:");

foreach (var p in TeamCity.Environment.Build.BuildProperties)
{
    Information("  - {0}={1}", p.Key, p.Value);
}

Information("");
Information("---");
Information("");

Information("TeamCity.Environment.Build.ConfigProperties:");

foreach (var p in TeamCity.Environment.Build.ConfigProperties)
{
    Information("  - {0}={1}", p.Key, p.Value);
}

Information("");
Information("---");
Information("");

Information("TeamCity.Environment.Build.RunnerProperties:");

foreach (var p in TeamCity.Environment.Build.RunnerProperties)
{
    Information("  - {0}={1}", p.Key, p.Value);
}
```

### Build log:

- `teamcity-build.log` (_content sampled_)

```
[Step 1/1] TeamCity.Environment.Build.BranchName: develop
[Step 1/1] TeamCity.Environment.Build.VcsBranchName: refs/heads/develop
[Step 1/1]
[Step 1/1] ---
[Step 1/1]
[Step 1/1] TeamCity.Environment.Build.BuildProperties:
[Step 1/1]   - agent.home.dir=D:\TeamCity\buildAgent01
[Step 1/1]   - agent.name=AUGUSTO-TC-01
[Step 1/1]   - teamcity.version=2020.2.2 (build 85899)
[Step 1/1]
[Step 1/1] ---
[Step 1/1]
[Step 1/1] TeamCity.Environment.Build.ConfigProperties:
[Step 1/1]   - build.triggeredBy=C. Augusto Proiete
[Step 1/1]   - build.triggeredBy.username=augustoproiete
[Step 1/1]   - DotNetCLI_Path=C:\Program Files\dotnet\dotnet.exe
[Step 1/1]
[Step 1/1] ---
[Step 1/1]
[Step 1/1] TeamCity.Environment.Build.RunnerProperties:
[Step 1/1]   - teamcity.build.checkoutDir=D:\agent01\w\ad0d02f87a570f9d
[Step 1/1]   - teamcity.fail.exit.code=true
[Step 1/1]   - teamcity.step.mode=default
[Step 1/1]   - use.custom.script=true
[Step 1/1] Process exited with code 0
[23:47:05] : Publishing internal artifacts (1s)
[23:47:06] :     [Publishing internal artifacts] Publishing 1 file using [WebPublisher]
[23:47:06] :     [Publishing internal artifacts] Publishing 1 file using [ArtifactsCachePublisher]
[23:47:06] : Build finished
```

2021-02-17 04:18 UTC, augustoproiete approved these changes
LGTM!

2021-02-17 04:18 UTC, merged

2021-02-17 04:19 UTC, augustoproiete commented
@BlythMeister your changes have been merged, thanks for your contribution :+1: