(GH-3127) Add ResultsDirectory to VSTestSettings. (see #3127)
cake-build/cake pull request #3128
Opened 2021-02-12 17:47 UTC by soroshsabz

This PR resolved #3127

2021-02-12 18:28 UTC, soroshsabz commented
@devlead Please review it :)

thanks

2021-02-16 14:38 UTC, augustoproiete requested changes
Thanks @soroshsabz. LGTM.

Could you please squash the commits and rebase against latest `develop`?

2021-02-16 14:48 UTC, soroshsabz commented
@augustoproiete I done it.

2021-02-16 16:19 UTC, augustoproiete approved these changes
LGTM

2021-02-16 16:19 UTC, augustoproiete commented on src/Cake.Common/Tools/VSTest/VSTestRunner.cs
> +                builder.AppendSwitchQuoted("/ResultsDirectory", ":", settings.ResultsDirectory.MakeAbsolute(_environment).FullPath);
:+1: Looks good / prior art

2021-02-16 16:19 UTC, augustoproiete commented on src/Cake.Common/Tools/VSTest/VSTestSettings.cs
> +        public DirectoryPath ResultsDirectory { get; set; }
:+1: Matches command-line argument in VSTest-Console [docs](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options#ResultDirectory)

[![image](https://user-images.githubusercontent.com/177608/108090522-114f3e80-7051-11eb-8000-0e8ad6d67adb.png)](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options#ResultDirectory)

2021-02-16 16:19 UTC, merged

2021-02-16 16:20 UTC, augustoproiete commented
@soroshsabz your changes have been merged, thanks for your contribution :+1: