GH2578: Support version ranges with NuGet in-process installer
cake-build/cake pull request #3240
Opened 2021-03-06 21:01 UTC by gitfool

Fixes #2578. Derived from PR #2576 - brought up to date with some of my own tweaks and fixed integration tests.

2021-03-06 21:32 UTC, gitfool commented
Interesting. The integration tests ran successfully for me locally but the build servers are failing as described [here](https://github.com/cake-build/cake/pull/2576#issuecomment-530874433).

2021-03-07 19:31 UTC, gitfool commented
No packages to install after running content resolver:
```log
2021-03-07T19:03:49.8355121Z ========================================
2021-03-07T19:03:49.8356144Z Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T19:03:49.8357177Z ========================================
2021-03-07T19:03:49.8358381Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T19:03:49.8532672Z Executing: "D:/a/cake/cake/tests/integration/tools/Cake/Cake.exe" "C:/Users/RUNNER~1/AppData/Local/Temp/ba2008d6-07ef-4ed4-b92e-ba728c5340f3.cake" --verbosity=Diagnostic
2021-03-07T19:03:50.3598459Z Looking for modules...
2021-03-07T19:03:50.3976832Z No modules found to install.
2021-03-07T19:03:50.4076009Z Module directory does not exist.
2021-03-07T19:03:50.4203682Z Analyzing build script...
2021-03-07T19:03:50.4243327Z Analyzing C:/Users/runneradmin/AppData/Local/Temp/ba2008d6-07ef-4ed4-b92e-ba728c5340f3.cake...
2021-03-07T19:03:50.4441151Z Processing build script...
2021-03-07T19:03:50.4477216Z Installing addins...
2021-03-07T19:03:50.5665470Z Missing C:\Users\runneradmin\.nuget\packages\serilog\2.6.0\serilog.2.6.0.nupkg
2021-03-07T19:03:50.8424093Z   GET https://api.nuget.org/v3/registration5-gz-semver2/serilog/index.json
2021-03-07T19:03:51.0264648Z   OK https://api.nuget.org/v3/registration5-gz-semver2/serilog/index.json 173ms
2021-03-07T19:03:51.0622099Z   GET https://api.nuget.org/v3/registration5-gz-semver2/serilog/page/2.5.0-dev-00817/2.8.1-dev-01052.json
2021-03-07T19:03:51.1598923Z   OK https://api.nuget.org/v3/registration5-gz-semver2/serilog/page/2.5.0-dev-00817/2.8.1-dev-01052.json 97ms
2021-03-07T19:03:51.4725687Z   GET https://api.nuget.org/v3-flatcontainer/serilog/2.6.0/serilog.2.6.0.nupkg
2021-03-07T19:03:51.4810395Z   OK https://api.nuget.org/v3-flatcontainer/serilog/2.6.0/serilog.2.6.0.nupkg 8ms
2021-03-07T19:03:51.4944720Z Acquiring lock for the installation of Serilog 2.6.0
2021-03-07T19:03:51.5079193Z Acquired lock for the installation of Serilog 2.6.0
2021-03-07T19:03:51.5083195Z Installing Serilog 2.6.0.
2021-03-07T19:03:51.6396276Z Completed installation of Serilog 2.6.0
2021-03-07T19:03:51.8313820Z No packages to install after running content resolver.
2021-03-07T19:03:51.8347439Z Error: Cake.Core.CakeException: Failed to install addin 'Serilog'.
2021-03-07T19:03:51.8350244Z    at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath)
2021-03-07T19:03:51.8353143Z    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath)
2021-03-07T19:03:51.8356610Z    at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings)
2021-03-07T19:03:51.8360151Z    at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings)
2021-03-07T19:03:51.8362346Z    at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings)
2021-03-07T19:03:51.9224982Z An error occurred when executing task 'Cake.NuGet.InProcessInstaller.VersionPinExact'.
```

2021-03-07 20:48 UTC, gitfool commented
No assemblies found after running content resolver:
```log
2021-03-07T20:32:10.9905152Z ========================================
2021-03-07T20:32:10.9906011Z Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T20:32:10.9907105Z ========================================
2021-03-07T20:32:10.9908230Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T20:32:11.0087124Z Executing: "D:/a/cake/cake/tests/integration/tools/Cake/Cake.exe" "C:/Users/RUNNER~1/AppData/Local/Temp/1a5259c5-6914-4a91-9a0e-1d0d579cddf5.cake" --verbosity=Diagnostic
2021-03-07T20:32:11.5272760Z Looking for modules...
2021-03-07T20:32:11.5671243Z No modules found to install.
2021-03-07T20:32:11.5772631Z Module directory does not exist.
2021-03-07T20:32:11.5903701Z Analyzing build script...
2021-03-07T20:32:11.5940469Z Analyzing C:/Users/runneradmin/AppData/Local/Temp/1a5259c5-6914-4a91-9a0e-1d0d579cddf5.cake...
2021-03-07T20:32:11.6140806Z Processing build script...
2021-03-07T20:32:11.6177600Z Installing addins...
2021-03-07T20:32:11.7409483Z Missing C:\Users\runneradmin\.nuget\packages\serilog\2.6.0\serilog.2.6.0.nupkg
2021-03-07T20:32:12.0426102Z   GET https://api.nuget.org/v3/registration5-gz-semver2/serilog/index.json
2021-03-07T20:32:12.1843015Z   OK https://api.nuget.org/v3/registration5-gz-semver2/serilog/index.json 130ms
2021-03-07T20:32:12.2222229Z   GET https://api.nuget.org/v3/registration5-gz-semver2/serilog/page/2.5.0-dev-00817/2.8.1-dev-01052.json
2021-03-07T20:32:12.3102869Z   OK https://api.nuget.org/v3/registration5-gz-semver2/serilog/page/2.5.0-dev-00817/2.8.1-dev-01052.json 88ms
2021-03-07T20:32:12.6474844Z   GET https://api.nuget.org/v3-flatcontainer/serilog/2.6.0/serilog.2.6.0.nupkg
2021-03-07T20:32:12.6539543Z   OK https://api.nuget.org/v3-flatcontainer/serilog/2.6.0/serilog.2.6.0.nupkg 6ms
2021-03-07T20:32:12.6682015Z Acquiring lock for the installation of Serilog 2.6.0
2021-03-07T20:32:12.6825860Z Acquired lock for the installation of Serilog 2.6.0
2021-03-07T20:32:12.6829835Z Installing Serilog 2.6.0.
2021-03-07T20:32:12.8265944Z Completed installation of Serilog 2.6.0
2021-03-07T20:32:12.9879705Z Addin assemblies not found at C:/Users/RUNNER~1/AppData/Local/Temp/tools/Addins/Serilog.2.6.0.
2021-03-07T20:32:13.0161680Z Addin assemblies not found for tfm .NETFramework,Version=v4.6.1 and rid [NULL].
2021-03-07T20:32:13.0163237Z No assemblies found after running content resolver.
2021-03-07T20:32:13.0198512Z Error: Cake.Core.CakeException: Failed to install addin 'Serilog'.
2021-03-07T20:32:13.0201531Z    at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath)
2021-03-07T20:32:13.0204851Z    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath)
2021-03-07T20:32:13.0211019Z    at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings)
2021-03-07T20:32:13.0213320Z    at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings)
2021-03-07T20:32:13.0215214Z    at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings)
2021-03-07T20:32:13.0440532Z An error occurred when executing task 'Cake.NuGet.InProcessInstaller.VersionPinExact'.
```

2021-03-07 22:22 UTC, gitfool commented
Using a `TEMP` subdirectory solved the issue:
```log
2021-03-07T21:15:09.4378611Z ========================================
2021-03-07T21:15:09.4379422Z Cake.NuGet.InProcessInstaller.Setup
2021-03-07T21:15:09.4380252Z ========================================
2021-03-07T21:15:09.4381343Z Executing task: Cake.NuGet.InProcessInstaller.Setup
2021-03-07T21:15:09.4382832Z Creating directory D:/a/cake/cake/tests/integration/temp/Cake.NuGet.InProcessInstaller
2021-03-07T21:15:09.4384339Z Finished executing task: Cake.NuGet.InProcessInstaller.Setup
2021-03-07T21:15:09.4385182Z 
2021-03-07T21:15:09.4385638Z ========================================
2021-03-07T21:15:09.4386677Z Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T21:15:09.4387682Z ========================================
2021-03-07T21:15:09.4388887Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T21:15:09.4554023Z Executing: "D:/a/cake/cake/tests/integration/tools/Cake/Cake.exe" "D:/a/cake/cake/tests/integration/temp/Cake.NuGet.InProcessInstaller/build.cake" --verbosity=Diagnostic
2021-03-07T21:15:09.9912990Z Looking for modules...
2021-03-07T21:15:10.0302453Z No modules found to install.
2021-03-07T21:15:10.0401209Z Module directory does not exist.
2021-03-07T21:15:10.0530115Z Analyzing build script...
2021-03-07T21:15:10.0568522Z Analyzing D:/a/cake/cake/tests/integration/temp/Cake.NuGet.InProcessInstaller/build.cake...
2021-03-07T21:15:10.0716715Z Processing build script...
2021-03-07T21:15:10.0754851Z Installing addins...
2021-03-07T21:15:10.1989890Z Missing C:\Users\runneradmin\.nuget\packages\serilog\2.6.0\serilog.2.6.0.nupkg
2021-03-07T21:15:10.5107798Z   GET https://api.nuget.org/v3/registration5-gz-semver2/serilog/index.json
2021-03-07T21:15:10.6715758Z   OK https://api.nuget.org/v3/registration5-gz-semver2/serilog/index.json 149ms
2021-03-07T21:15:10.7111812Z   GET https://api.nuget.org/v3/registration5-gz-semver2/serilog/page/2.5.0-dev-00817/2.8.1-dev-01052.json
2021-03-07T21:15:10.7300841Z   OK https://api.nuget.org/v3/registration5-gz-semver2/serilog/page/2.5.0-dev-00817/2.8.1-dev-01052.json 19ms
2021-03-07T21:15:11.0762189Z   GET https://api.nuget.org/v3-flatcontainer/serilog/2.6.0/serilog.2.6.0.nupkg
2021-03-07T21:15:11.0893469Z   OK https://api.nuget.org/v3-flatcontainer/serilog/2.6.0/serilog.2.6.0.nupkg 13ms
2021-03-07T21:15:11.1035857Z Acquiring lock for the installation of Serilog 2.6.0
2021-03-07T21:15:11.1189930Z Acquired lock for the installation of Serilog 2.6.0
2021-03-07T21:15:11.1193590Z Installing Serilog 2.6.0.
2021-03-07T21:15:11.2575563Z Completed installation of Serilog 2.6.0
2021-03-07T21:15:11.3892780Z The addin Serilog will reference Serilog.dll.
2021-03-07T21:15:11.4058234Z Verifying assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
2021-03-07T21:15:11.4784561Z Adding assembly reference to mscorlib.dll...
2021-03-07T21:15:11.4786009Z Adding assembly reference to System.Core.dll...
2021-03-07T21:15:11.4787134Z Adding assembly reference to Microsoft.CSharp.dll...
2021-03-07T21:15:11.4788169Z Adding assembly reference to Cake.Core.dll...
2021-03-07T21:15:11.4789149Z Adding assembly reference to Cake.Common.dll...
2021-03-07T21:15:11.4790078Z Adding assembly reference to Cake.exe...
2021-03-07T21:15:11.4790970Z Adding assembly reference to System.dll...
2021-03-07T21:15:11.4791878Z Adding assembly reference to System.Xml.dll...
2021-03-07T21:15:11.4792893Z Adding assembly reference to System.Xml.Linq.dll...
2021-03-07T21:15:11.4793893Z Adding assembly reference to System.Data.dll...
2021-03-07T21:15:11.4794982Z Adding assembly reference to System.Runtime.dll...
2021-03-07T21:15:11.4796061Z Adding assembly reference to System.Collections.dll...
2021-03-07T21:15:11.4806170Z Adding assembly reference to System.Net.Http.dll...
2021-03-07T21:15:11.4807396Z Adding assembly reference to netstandard.dll...
2021-03-07T21:15:11.4808317Z Adding assembly reference to Serilog.dll...
2021-03-07T21:15:11.4812282Z Importing namespace Cake.Common...
2021-03-07T21:15:11.4813260Z Importing namespace Cake.Common.Build...
2021-03-07T21:15:11.4814335Z Importing namespace Cake.Common.Build.AppVeyor...
2021-03-07T21:15:11.4815732Z Importing namespace Cake.Common.Build.AppVeyor.Data...
2021-03-07T21:15:11.4817140Z Importing namespace Cake.Common.Build.AzurePipelines...
2021-03-07T21:15:11.4818650Z Importing namespace Cake.Common.Build.AzurePipelines.Data...
2021-03-07T21:15:11.4819996Z Importing namespace Cake.Common.Build.Bamboo...
2021-03-07T21:15:11.4821196Z Importing namespace Cake.Common.Build.Bamboo.Data...
2021-03-07T21:15:11.4822601Z Importing namespace Cake.Common.Build.BitbucketPipelines...
2021-03-07T21:15:11.4824252Z Importing namespace Cake.Common.Build.BitbucketPipelines.Data...
2021-03-07T21:15:11.4825743Z Importing namespace Cake.Common.Build.Bitrise...
2021-03-07T21:15:11.4826979Z Importing namespace Cake.Common.Build.Bitrise.Data...
2021-03-07T21:15:11.4828246Z Importing namespace Cake.Common.Build.ContinuaCI...
2021-03-07T21:15:11.4829581Z Importing namespace Cake.Common.Build.ContinuaCI.Data...
2021-03-07T21:15:11.4830939Z Importing namespace Cake.Common.Build.GitHubActions...
2021-03-07T21:15:11.4832615Z Importing namespace Cake.Common.Build.GitHubActions.Data...
2021-03-07T21:15:11.4834011Z Importing namespace Cake.Common.Build.GitLabCI...
2021-03-07T21:15:11.4835622Z Importing namespace Cake.Common.Build.GitLabCI.Data...
2021-03-07T21:15:11.4836826Z Importing namespace Cake.Common.Build.GoCD...
2021-03-07T21:15:11.4838009Z Importing namespace Cake.Common.Build.GoCD.Data...
2021-03-07T21:15:11.4839181Z Importing namespace Cake.Common.Build.Jenkins...
2021-03-07T21:15:11.4840414Z Importing namespace Cake.Common.Build.Jenkins.Data...
2021-03-07T21:15:11.4841608Z Importing namespace Cake.Common.Build.MyGet...
2021-03-07T21:15:11.4842759Z Importing namespace Cake.Common.Build.TeamCity...
2021-03-07T21:15:11.4843935Z Importing namespace Cake.Common.Build.TravisCI...
2021-03-07T21:15:11.4845261Z Importing namespace Cake.Common.Build.TravisCI.Data...
2021-03-07T21:15:11.4846460Z Importing namespace Cake.Common.Diagnostics...
2021-03-07T21:15:11.4847455Z Importing namespace Cake.Common.IO...
2021-03-07T21:15:11.4848415Z Importing namespace Cake.Common.IO.Paths...
2021-03-07T21:15:11.4849425Z Importing namespace Cake.Common.Net...
2021-03-07T21:15:11.4850392Z Importing namespace Cake.Common.Security...
2021-03-07T21:15:11.4851453Z Importing namespace Cake.Common.Solution...
2021-03-07T21:15:11.4852582Z Importing namespace Cake.Common.Solution.Project...
2021-03-07T21:15:11.4854057Z Importing namespace Cake.Common.Solution.Project.Properties...
2021-03-07T21:15:11.4855773Z Importing namespace Cake.Common.Solution.Project.XmlDoc...
2021-03-07T21:15:11.4857002Z Importing namespace Cake.Common.Text...
2021-03-07T21:15:11.4858011Z Importing namespace Cake.Common.Tools.Cake...
2021-03-07T21:15:11.4859186Z Importing namespace Cake.Common.Tools.Chocolatey...
2021-03-07T21:15:11.4860553Z Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
2021-03-07T21:15:11.4862090Z Importing namespace Cake.Common.Tools.Chocolatey.Config...
2021-03-07T21:15:11.4863585Z Importing namespace Cake.Common.Tools.Chocolatey.Download...
2021-03-07T21:15:11.4865226Z Importing namespace Cake.Common.Tools.Chocolatey.Features...
2021-03-07T21:15:11.4866782Z Importing namespace Cake.Common.Tools.Chocolatey.Install...
2021-03-07T21:15:11.4868247Z Importing namespace Cake.Common.Tools.Chocolatey.New...
2021-03-07T21:15:11.4869652Z Importing namespace Cake.Common.Tools.Chocolatey.Pack...
2021-03-07T21:15:11.4871021Z Importing namespace Cake.Common.Tools.Chocolatey.Pin...
2021-03-07T21:15:11.4872421Z Importing namespace Cake.Common.Tools.Chocolatey.Push...
2021-03-07T21:15:11.4873901Z Importing namespace Cake.Common.Tools.Chocolatey.Sources...
2021-03-07T21:15:11.4878142Z Importing namespace Cake.Common.Tools.Chocolatey.Uninstall...
2021-03-07T2 [...]

2021-03-07 23:41 UTC, gitfool commented
Extract from relevant integration tests with diagnostics logging:
```log
2021-03-07T21:15:09.4385638Z ========================================
2021-03-07T21:15:09.4386677Z Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T21:15:09.4387682Z ========================================
2021-03-07T21:15:09.4388887Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T21:15:10.0530115Z Analyzing build script...
2021-03-07T21:15:10.0754851Z Installing addins...
2021-03-07T21:15:11.1193590Z Installing Serilog 2.6.0.
2021-03-07T21:15:11.2575563Z Completed installation of Serilog 2.6.0
2021-03-07T21:15:11.3892780Z The addin Serilog will reference Serilog.dll.
2021-03-07T21:15:11.4058234Z Verifying assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
2021-03-07T21:15:16.5815639Z Requested NuGet version: 2.6.0
2021-03-07T21:15:16.5816454Z Loaded NuGet version: 2.6.0.0
2021-03-07T21:15:16.6081671Z Finished executing task: Cake.NuGet.InProcessInstaller.VersionPinExact
2021-03-07T21:15:16.6083095Z 
2021-03-07T21:15:16.6083684Z ========================================
2021-03-07T21:15:16.6085232Z Cake.NuGet.InProcessInstaller.VersionPinRange.InclusiveExclusive
2021-03-07T21:15:16.6086922Z ========================================
2021-03-07T21:15:16.6088773Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinRange.InclusiveExclusive
2021-03-07T21:15:17.2180209Z Analyzing build script...
2021-03-07T21:15:17.2418241Z Installing addins...
2021-03-07T21:15:18.5458915Z Installing Serilog 2.5.0.
2021-03-07T21:15:18.7644863Z Completed installation of Serilog 2.5.0
2021-03-07T21:15:18.9019066Z The addin Serilog will reference Serilog.dll.
2021-03-07T21:15:18.9196765Z Verifying assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
2021-03-07T21:15:24.0680121Z Requested NuGet version: [2.5.0,2.6.0)
2021-03-07T21:15:24.0680919Z Loaded NuGet version: 2.5.0.0
2021-03-07T21:15:24.0959473Z Finished executing task: Cake.NuGet.InProcessInstaller.VersionPinRange.InclusiveExclusive
2021-03-07T21:15:24.0961735Z 
2021-03-07T21:15:24.0962306Z ========================================
2021-03-07T21:15:24.0963885Z Cake.NuGet.InProcessInstaller.VersionPinRange.InclusiveInclusive
2021-03-07T21:15:24.0965543Z ========================================
2021-03-07T21:15:24.0967289Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinRange.InclusiveInclusive
2021-03-07T21:15:24.7156404Z Analyzing build script...
2021-03-07T21:15:24.7384736Z Installing addins...
2021-03-07T21:15:25.9063946Z Installing Serilog 2.3.0.
2021-03-07T21:15:26.0864300Z Completed installation of Serilog 2.3.0
2021-03-07T21:15:26.2227948Z The addin Serilog will reference Serilog.dll.
2021-03-07T21:15:26.2398480Z Verifying assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
2021-03-07T21:15:31.3795549Z Requested NuGet version: [2.3.0,2.4.0]
2021-03-07T21:15:31.3796318Z Loaded NuGet version: 2.3.0.0
2021-03-07T21:15:31.4090551Z Finished executing task: Cake.NuGet.InProcessInstaller.VersionPinRange.InclusiveInclusive
2021-03-07T21:15:31.4092692Z 
2021-03-07T21:15:31.4094826Z ========================================
2021-03-07T21:15:31.4097481Z Cake.NuGet.InProcessInstaller.VersionPinRange.Wildcard
2021-03-07T21:15:31.4098847Z ========================================
2021-03-07T21:15:31.4100353Z Executing task: Cake.NuGet.InProcessInstaller.VersionPinRange.Wildcard
2021-03-07T21:15:32.0246831Z Analyzing build script...
2021-03-07T21:15:32.0469206Z Installing addins...
2021-03-07T21:15:33.2097268Z Installing Serilog 2.2.1.
2021-03-07T21:15:33.3855648Z Completed installation of Serilog 2.2.1
2021-03-07T21:15:33.5222173Z The addin Serilog will reference Serilog.dll.
2021-03-07T21:15:33.5389026Z Verifying assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
2021-03-07T21:15:38.6528191Z Requested NuGet version: [2.2.*,2.3.0)
2021-03-07T21:15:38.6529017Z Loaded NuGet version: 2.2.1.0
2021-03-07T21:15:38.6817919Z Finished executing task: Cake.NuGet.InProcessInstaller.VersionPinRange.Wildcard
```
See [logs_975.zip](https://github.com/cake-build/cake/files/6098163/logs_975.zip) for the full logs from successful build with diagnostics logging.

Also, note that NuGet [dependency resolution rules](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#dependency-resolution-rules) seem to be using "lowest applicable version" to resolve version `[2.3.0,2.4.0]` in `VersionPinRange.InclusiveInclusive`.

@augustoproiete ready for review.

2021-03-08 20:10 UTC, gitfool commented
Unrelated build failure in `macos-latest`:
```log
2021-03-08T19:48:58.5777150Z ----------------------------------------
2021-03-08T19:48:58.5777640Z Teardown
2021-03-08T19:48:58.5778430Z ----------------------------------------
2021-03-08T19:48:58.5786430Z Starting Teardown...
2021-03-08T19:48:58.5787820Z Finished running tasks.
2021-03-08T19:48:58.5814550Z Error: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 1).)
2021-03-08T19:48:58.5816140Z 	.NET Core CLI: Process returned an error (exit code 1).
2021-03-08T19:48:58.6121560Z ##[error]The process 'tools/dotnet-cake' failed with exit code 1
```
I've seen this before; seems to happen randomly.

2021-03-09 08:17 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
I was using `??=` in the code at one point which required a newer / latest lang version. I noticed it wasn't enabled consistently across all projects so I moved it to `Directory.Build.props` and removed it from projects.

2021-03-09 08:21 UTC, devlead requested changes

2021-03-09 08:23 UTC, devlead commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
Are we sure this will have zero multitargeting side effects?

2021-03-09 08:30 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
I've always used it across targets. If I read [an update to C# versions and C# tooling](https://devblogs.microsoft.com/dotnet/an-update-to-c-versions-and-c-tooling/) correctly, then the target framework determines what is actually supported.

2021-03-09 08:32 UTC, devlead commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
Ok, excellent just making sure so IL doesn't change so we need to bump the Mono version or similar.

2021-03-09 08:50 UTC, gitfool commented on tests/integration/Cake.NuGet/InProcessInstaller.cake
> +    CakeExecuteScript(scriptPath);
Done.

2021-03-09 09:09 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
You're making me doubt this change now. After re-reading [C# language versioning defaults](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults) and specifically:
> Visual Studio 2017 added a <LangVersion>latest</LangVersion> entry to any project files it created. That meant C# 7.0 when it was added. However, once you upgrade to Visual Studio 2019, that means the latest released version, regardless of the target framework. These projects now override the default behavior. **You should edit the project file and remove that node. Then, your project will use the compiler version recommended for your target framework.**

Makes me wonder if the better option is to simply _remove_ `LangVersion` from all projects so they use defaults based on target framework.

2021-03-09 09:10 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
@devlead thoughts?

2021-03-09 09:37 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
I force pushed again to remove the change to `Directory.Build.props`. 😅

2021-03-09 09:43 UTC, devlead commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
Ok :) Just let us know when ready for review again.

2021-03-09 09:47 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
That works as expected - I get squiggles in Visual Studio depending on what target framework is currently selected.

2021-03-09 09:52 UTC, gitfool commented on src/Directory.Build.props
> +    <LangVersion>latest</LangVersion>
I guess I've not been using the latest C# features that require library or runtime support hence I've been getting away it.

2021-03-09 10:12 UTC, devlead approved these changes
LGTM 👍

2021-03-09 10:17 UTC, merged

2021-03-09 10:17 UTC, devlead commented
@gitfool your changes have been merged, thanks for your contribution 👍