Add Support for TestParams flag in NUnit3
cake-build/cake pull request #3339
Opened 2021-05-07 02:55 UTC by joshuacookdev

Resolves #2654.

I wasn't sure if it was better to add TestParams as its own property, or to convert the Params to the new `--testparam:key=value` syntax in NUnit v3.10+. I opted for creating a new property so that we have support for both, but am willing to change to converting the output if that's deemed better. 

As it stands, the only issue that I can see with this is that we might make it confusing to allow both, but this was allows us to support multiple versions of the runner, and lets Cake scripts migrate as they're ready (for now) without any breaking changes.

2021-05-07 03:02 UTC, joshuacookdev commented
Sorry, had to fix a typo.

2021-05-07 03:59 UTC, joshuacookdev commented
Didn't realize that including an obsolete tag would fail all of those builds...

2021-05-25 18:40 UTC, devlead requested changes
@joshuacookdev could you please rebase and squash commits against latest develop branch.

2021-05-25 22:35 UTC, devlead approved these changes
LGTM 👍

2021-05-25 22:53 UTC, merged

2021-05-25 22:54 UTC, devlead commented
@joshuacookdev your changes have been merged, thanks for your contribution 👍