GHxxxx: Add support for Chocolatey Export Command
cake-build/cake pull request #3768
Opened 2021-12-15 07:25 UTC by gep13

This command was added in 0.11.0 of Chocolatey, providing the ability
for a user to export a file that contains information about all the
currently installed Chocolatey packages on a machine.

This information can be useful, therefore creating a Cake alias to
support it makes sense.

2021-12-15 07:26 UTC, gep13 commented
**NOTE:** I need to create an issue to go along with this, but wanted to open the draft PR to start running through all the unit tests :smile:

2021-12-20 16:13 UTC, devlead requested changes
In general LGTM 👍 
Some minor comments.

Maybe add an integration test something like `tests\integration\Cake.Common\Tools\Chocolatey\ChocolateyAliases.cake`
```cake
#load "./../../../utilities/paths.cake"
#load "./../../../utilities/xunit.cake"

Task("Cake.Common.Tools.Chocolatey.ChocolateyAliases.ChocolateyExport")
    .Does(() => {
    // Given
    var directoryPath = Paths.Temp.Combine("./Cake.Common/Tools/Chocolatey/ChocolateyExport");
    var filePath = directoryPath.CombineWithFilePath("packages.config");
    EnsureDirectoryExists(directoryPath);

    var settings = new ChocolateyExportSettings {
        OutputFilePath = filePath.FullPath
    };

    // When
    ChocolateyExport(settings);

    // Then
    Assert.True(FileExists(filePath), $"{filePath.FullPath} missing");
});


var chocolateyAliasesTask = Task("Cake.Common.Tools.Chocolatey.ChocolateyAliases");

if (IsRunningOnWindows() && Context.Tools.Resolve("choco.exe") is FilePath)
{
    chocolateyAliasesTask
        .IsDependentOn("Cake.Common.Tools.Chocolatey.ChocolateyAliases.ChocolateyExport");
}

```

2021-12-20 16:16 UTC, gep13 commented on src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
> +        public string CacheLocation { get; set; }
So, I thought about this when I was writing this, however, the existing aliases don't use FilePath/DirectoryPath, so I thought from a consistency point of view, better to stay the same.

2021-12-26 12:12 UTC, devlead commented on src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
> +        public string CacheLocation { get; set; }
One can assign a string to a FilePath but not the other way around. Directory / FilePath indicates intent, if it's a file or directory, at least the xml comment should indicate if it's a file or directory.

And we probably for 3.0 should address the other settings classes then.

2021-12-26 13:05 UTC, gep13 commented on src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
> +        public string CacheLocation { get; set; }
I actually went back and checked this. The other settings classes are actually using FilePath/DirectoryPath in most places, but there is one place where it isn't, with the CacheLocation, so perhaps there was a reason that this was left as a string. I would need to go back and check.

I will get this PR updated with your suggestions.

2022-02-07 20:15 UTC, gep13 commented on src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
> +        /// Gets or sets teh path to the file that will be generated.
:+1:

2022-02-07 20:16 UTC, gep13 commented on src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
> +        public string OutputFilePath { get; set; }
:+1:

2022-02-07 20:20 UTC, gep13 commented on src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
> +        public string CacheLocation { get; set; }
On the stream tonight, we checked, and CacheLocation is indeed a string in the other settings classes for Chocolatey, so I am going to suggest that we leave this as a string here, and instead, take another task to update it everywhere.

2022-02-08 07:26 UTC, nils-a commented
@gep13 I added https://github.com/cake-build/cake/pull/3768/commits/d3e558b20992c2884de278bed8b5159450d9b145 to let the integration tests pick up on the `Cake.Chocolatey.*` tests.

2022-02-08 07:33 UTC, gep13 commented
@nils-a thanks for getting that added! Does this mean that the integration tests are being run on each CI system, or are they still only being run in a few places? Just want to know where I can "see" the results.

2022-02-08 07:58 UTC, nils-a commented
They run on DevOps for the Windows, Ubuntu and Mac pipelines, as well as the GitHub pipelines.

(And, naturally, I missed a spot there... So "now" they should run during the integration tests.)

2022-02-15 07:45 UTC, devlead approved these changes
LGTM 👍

2022-02-15 08:04 UTC, merged

2022-02-15 08:04 UTC, devlead commented
@gep13 your changes have been merged, thanks for your contribution 👍