GH3947: Add Command aliases
cake-build/cake pull request #3948
Opened 2022-08-22 15:38 UTC by devlead

* fixes #3947 by adding new command aliases 

Command aliases in this PR are between StartProcess and the out-of-the-box typed aliases, it lets you benefit from Cake's built-in tool resolution making it easier to support tools with different executables i.e. Posix/Windows or installed using tool directive. It will default fail the build on non-zero exit codes, providing more convenient access to standard output/error.

Intentionally didn't seal `CommandSettings` as one possibly could create one's own typed settings with defaults for reuse.
Settings class in general makes it easier to reuse a tool across tasks, but there are also alias variants that just take the tool executable names.

PR also adds some ToolSettings Extensions, making it easier to work with tool settings in customization scenarios.

Unsure if ready for review, will read through the code again, but certainly ready for feedback :) 

## Examples just executing tools

### Example With ProcessArgumentBuilder

```cake
#tool dotnet:?package=DPI&version=2022.8.21.54
Command(
    new []{ "dpi", "dpi.exe"},
    new ProcessArgumentBuilder()
        .Append("nuget")
        .AppendQuoted(Context.Environment.WorkingDirectory.FullPath)
        .AppendSwitch("--output", " ", "TABLE")
        .Append("analyze")
);
```

### Example With implicit ProcessArgumentBuilder

```cake
Command(
    new []{ "dotnet", "dotnet.exe"},
    "--version"
);
```

### Example specify expected exit code

```cake
Command(
    new []{ "dotnet", "dotnet.exe"},
    expectedExitCode: -2147450751
);
```

### Example settings customization

```cake
Command(
    new []{ "dotnet", "dotnet.exe"},
    settingsCustomization: settings => settings
                                            .WithToolName(".NET tool")
                                            .WithExpectedExitCode(1)
                                            .WithArgumentCustomization(args => args.Append("tool"))
);
```

### Example reusable tools settings i.e. created in setup.

```cake
#tool dotnet:?package=DPI&version=2022.8.21.54
// Reusable tools settings i.e. created in setup.
var settings = new CommandSettings {
        ToolName = "DPI",
        ToolExecutableNames =  new []{ "dpi", "dpi.exe"},
     };

// Example With ProcessArgumentBuilder
Command(
    settings,
    new ProcessArgumentBuilder()
         .Append("nuget")
         .AppendQuoted(Context.Environment.WorkingDirectory.FullPath)
         .AppendSwitch("--output", " ", "TABLE")
         .Append("analyze")
);

// Example With implicit ProcessArgumentBuilder
Command(
     settings,
     $"nuget --output TABLE analyze"
);
```

## Examples handling standard output

### Examples specifying tool executable names

```cake
using System.Text.Json.Serialization;
using System.Text.Json;
#tool dotnet:?package=DPI&version=2022.8.21.54

// Example With ProcessArgumentBuilder
var exitCode = Command(
    new []{ "dpi", "dpi.exe"},
    out var standardOutput,
    new ProcessArgumentBuilder()
         .Append("nuget")
         .AppendQuoted(Context.Environment.WorkingDirectory.FullPath)
         .AppendSwitch("--output", " ", "JSON")
         .Append("analyze")
);

var packageReferences =  JsonSerializer.Deserialize<DPIPackageReference[]>(
    standardOutput
);

// Example With implicit ProcessArgumentBuilder
var implicitExitCode = Command(
     new []{ "dpi", "dpi.exe"},
     out var implicitStandardOutput,
     $"nuget --output JSON analyze"
);

var implicitPackageReferences =  JsonSerializer.Deserialize<DPIPackageReference[]>(
    implicitStandardOutput
);

// Example settings customization
var settingsCustomizationExitCode = Command(
    new []{ "dpi", "dpi.exe"},
    out var settingsCustomizationStandardOutput,
    $"nuget --output JSON analyze",
    settingsCustomization: settings => settings
                                            .WithToolName("DPI")
                                            .WithArgumentCustomization(args => args.AppendSwitchQuoted("--buildversion", " ", "1.0.0"))
);

var settingsCustomizationPackageReferences =  JsonSerializer.Deserialize<DPIPackageReference[]>(
    settingsCustomizationStandardOutput
);

// Record used in example above
public record DPIPackageReference(
    [property: JsonPropertyName("source")]
    string Source,
    [property: JsonPropertyName("sourceType")]
    string SourceType,
    [property: JsonPropertyName("packageId")]
    string PackageId,
    [property: JsonPropertyName("version")]
    string Version
);
```

### Examples reusable tools settings i.e. created in setup.

```cake
using System.Text.Json.Serialization;
using System.Text.Json;
#tool dotnet:?package=DPI&version=2022.8.21.54
// Reusable tools settings i.e. created in setup.
var settings = new CommandSettings {
        ToolName = "DPI",
        ToolExecutableNames =  new []{ "dpi", "dpi.exe"},
     };

// Example With ProcessArgumentBuilder
var exitCode = Command(
    settings,
    out var standardOutput,
    new ProcessArgumentBuilder()
         .Append("nuget")
         .AppendQuoted(Context.Environment.WorkingDirectory.FullPath)
         .AppendSwitch("--output", " ", "JSON")
         .Append("analyze")
);

var packageReferences =  JsonSerializer.Deserialize<DPIPackageReference[]>(
    standardOutput
);

// Example With implicit ProcessArgumentBuilder
var implicitExitCode = Command(
     settings,
     out var implicitStandardOutput,
     $"nuget --output JSON analyze"
);

var implicitPackageReferences =  JsonSerializer.Deserialize<DPIPackageReference[]>(
    implicitStandardOutput
);

// Record used in example above
public record DPIPackageReference(
    [property: JsonPropertyName("source")]
    string Source,
    [property: JsonPropertyName("sourceType")]
    string SourceType,
    [property: JsonPropertyName("packageId")]
    string PackageId,
    [property: JsonPropertyName("version")]
    string Version
);
```

## Examples handling standard error

### Examples specifying tool executable names

```cake
// Example With ProcessArgumentBuilder
var exitCode = Command(
    new []{ "dotnet", "dotnet.exe" },
    out var standardOutput,
    out var standardError,
    new ProcessArgumentBuilder()
        .Append("tool"),
    expectedExitCode:1
);

Verbose("Exit code: {0}", exitCode);
Information("Output: {0}", standardOutput);
Error("Error: {0}", standardError);

// Example With implicit ProcessArgumentBuilder
var implicitExitCode = Command(
    new []{ "dotnet", "dotnet.exe" },
    out var implicitStandardOutput,
    out var implicitStandardError,
    "tool",
    expectedExitCode:1
);

Verbose("Exit code: {0}", implicitExitCode);
Information("Output: {0}", implicitStandardOutput);
Error("Error: {0}", implicitStandardError);

// Example settings customization
var settingsCustomizationExitCode = Command(
    new []{ "dotnet", "dotnet.exe" },
    out var settingsCustomizationStandardOutput,
    out var settingsCustomizationStandardError,
    settingsCustomization: settings => settings
                                        .WithToolName(".NET Tool")
                                        .WithArgumentCustomization(args => args.Append("tool"))
                                        .WithExpectedExitCode(1)
);

Verbose("Exit code: {0}", settingsCustomizationExitCode);
Information("Output: {0}", settingsCustomizationStandardOutput);
Error("Error: {0}", settingsCustomizationStandardError);
```

### Examples reusable tools settings i.e. created in setup.

```cake
// Reusable tools settings i.e. created in setup.
var settings = new CommandSettings {
        ToolName = ".NET CLI",
        ToolExecutableNames =  new []{ "dotnet", "dotnet.exe" },
     }.WithExpectedExitCode(1);

// Example With ProcessArgumentBuilder
var exitCode = Command(
    settings,
    out var standardOutput,
    out var standardError,
    new ProcessArgumentBuilder()
        .Append("tool")
);

Verbose("Exit code: {0}", exitCode);
Information("Output: {0}", standardOutput);
Error("Error: {0}", standardError);

// Example With imp [...]

2022-08-22 20:21 UTC, gep13 requested changes
A few things that I noticed when reviewing this PR.

One general request...

There are a few places where you use `expectExitCode` and others where you use `expectedExitCode`.  Can we make sure to use `expected` in all the places?

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardOutputFixtureExtentions.cs
> +            fixture.ProcessRunner.Process.SetStandardError(standardOutput);
```suggestion
            fixture.ProcessRunner.Process.SetStandardError(standardError);
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
> +            const string expectStandard = "LINE1";
```suggestion
            const string expectStandardOutput = "LINE1";
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
> +            const string expectStandard = "LINE1";
```suggestion
            const string expectStandardOutput = "LINE1";
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
> +            const string expectError = "ERRORLINE1";
```suggestion
            const string expectStandardError = "ERRORLINE1";
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
> +            const string expectStandard = "LINE1";
```suggestion
            const string expectStandardOutput = "LINE1";
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
> +            const string expectError = "ERRORLINE1";
```suggestion
            const string expectStandardError = "ERRORLINE1";
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerFixture.cs
> +﻿using System.Collections.Generic;
Missing license header.

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardErrorFixture.cs
> +﻿namespace Cake.Common.Tests.Fixtures.Tools.Command
Missing license header.

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardOutFixture.cs
> +﻿namespace Cake.Common.Tests.Fixtures.Tools.Command
Missing license header.

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardOutputFixtureExtentions.cs
> +﻿namespace Cake.Common.Tests.Fixtures.Tools.Command
Missing license header.

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
> +﻿using System;
Missing license header.

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Core/Tooling/ToolSettingsExtensions.cs
> +        /// Sets the whether the tool should use working directory.
Can we fix this up? Doesn't read right to me.

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Core/Tooling/ToolSettingsExtensions.cs
> +        /// Sets the tool environment variable.
"Sets or adds tool environment variable?"

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common/Tools/Command/CommandAliases.cs
> +        /// // Example With ProcessArgumentBuilder
```suggestion
        /// // Example with ProcessArgumentBuilder
```

2022-08-22 20:21 UTC, gep13 commented on src/Cake.Common/Tools/Command/CommandAliases.cs
> +        /// // Example With implicit ProcessArgumentBuilder
```suggestion
        /// // Example with implicit ProcessArgumentBuilder
```

2022-08-22 21:20 UTC, devlead commented
@gep13 PR feedback should be addressed.

2022-09-04 19:12 UTC, gep13 approved these changes
LGTM!

2022-09-04 19:13 UTC, gep13 commented
@devlead thanks for getting all those those thing fixed up! This looks good to me!

2022-09-04 19:13 UTC, merged