fix: disable report printing if verbosity of logger is Quiet
cake-build/cake pull request #4148
Opened 2023-04-14 20:26 UTC by deniszykov

fix for https://github.com/cake-build/cake/issues/2101

2023-04-14 20:27 UTC, deniszykov commented
@microsoft-github-policy-service agree

2023-04-19 14:17 UTC, augustoproiete requested changes, later dismissed

2023-04-19 14:17 UTC, augustoproiete commented on src/Cake.Core/CakeReportPrinter.cs
> +
Thanks for the PR @deniszykov! As you can see in [this comment in the original issue](https://github.com/cake-build/cake/issues/2101#issuecomment-376160140) we wouldn't want to change the semantics of the `Quiet` verbosity in order to hide the report - this means users don't have a way to suppress the log messages and see the report anymore.

Could you add a new command-line argument to Cake called `--no-report` that hides the report? (regardless of the Verbosity)

2025-12-06 16:54 UTC, gep13 commented on src/Cake.Core/CakeReportPrinter.cs
> +
I have taken the liberty to update this PR with the suggested changes.

2025-12-06 16:55 UTC, gep13 commented
@deniszykov rather than create a new PR, I have taken the liberty to update this PR using the suggested approach discussed in the original issue.

Please let me know if you have any concerns about me doing this.

2025-12-06 17:00 UTC, deniszykov commented
> @deniszykov rather than create a new PR, I have taken the liberty to update this PR using the suggested approach discussed in the original issue.
> 
> Please let me know if you have any concerns about me doing this.

I don't mind, and thanks. I was actually thinking of adding another logging level below Quiet.  But I solved my problem differently and forgot about this PR.

2025-12-06 17:21 UTC, gep13 commented
@deniszykov said...
I don't mind, and thanks.

Perfect! I have started a process of reviewing some of the older PR's that we have, and I stumbled across your one.

2025-12-06 18:16 UTC, gep13 commented on src/Cake.Cli/Hosts/BuildScriptHost.cs
> +                var noReportEnabled = _configuration.GetValue("Settings_NoReport") ?? bool.FalseString;
@devlead I tried to use the `Constants` class here, rather than the hard coded `Settings_NoReport`, but it is marked `internal`.  Should I create a new `Constants` class in the Cake.Cli project?

2025-12-10 12:47 UTC, devlead commented on src/Cake.Cli/Hosts/BuildScriptHost.cs
> +                var noReportEnabled = _configuration.GetValue("Settings_NoReport") ?? bool.FalseString;
@gep13 If it's just used in Cake.Cli it makes sense to add a new Constants class in Cake.Cli project.

2026-03-03 21:27 UTC, devlead approved these changes
LGMT 👍

2026-03-03 21:29 UTC, merged

2026-03-03 21:29 UTC, devlead commented
@deniszykov & @gep13  your changes have been merged, thanks for your contribution 👍