Allow for empty properties in dotnet msbuild
cake-build/cake pull request #4165
Opened 2023-06-04 01:58 UTC by Zulu-Inuoe

Fixes #4158

2023-06-04 02:00 UTC, Zulu-Inuoe commented
@microsoft-github-policy-service agree

2023-06-06 04:25 UTC, augustoproiete requested changes, later dismissed
Thanks for the PR @Zulu-Inuoe 

Overall looks good, but there's at least one test failing (which expects the old behavior). Could you take a look and amend the test(s) (or delete if doesn't make sense anymore)?

```
Actual:   (null)
  Stack Trace:
     at Cake.Common.Tests.Unit.Tools.DotNet.MSBuild.DotNetMSBuildBuilderTests.TheBuildMethod.Should_Throw_If_Property_Has_No_Value(String[] propertyValues) in D:\a\1\s\src\Cake.Common.Tests\Unit\Tools\DotNet\MSBuild\DotNetMSBuildBuilderTests.cs:line 204
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Failed Cake.Common.Tests.Unit.Tools.DotNet.MSBuild.DotNetMSBuildBuilderTests+TheBuildMethod.Should_Throw_If_Property_Has_No_Value(propertyValues: [""]) [< 1 ms]
  Error Message:
   Assert.IsType() Failure
Expected: System.ArgumentException
```

2023-07-31 18:42 UTC, augustoproiete commented
Hey @Zulu-Inuoe just following up on this one. Will you be able to get this to the finish line?

2026-03-08 17:27 UTC, devlead approved these changes
Addressed the failing test.
LGTM 👍

2026-03-08 17:28 UTC, merged

2026-03-08 17:35 UTC, devlead commented
@Zulu-Inuoe your changes have been merged, thanks for your contribution 👍