Add NodeReuse property to DotNetMSBuildSettings
cake-build/cake pull request #4194
Opened 2023-07-16 00:49 UTC by Marusyk

Add NodeReuse property to DotNetMSBuildSettings and tests

Fixes #4144 

Please review,
Thank you in advance

2023-07-16 07:25 UTC, augustoproiete requested changes
LGTM overall. Small change on the command-line

2023-07-16 07:25 UTC, augustoproiete commented on src/Cake.Common/Tools/DotNet/MSBuild/MSBuildArgumentBuilderExtensions.cs
> +            }
```suggestion
            // Re-use of MSBuild nodes?
            if (settings.NodeReuse.HasValue)
            {
                msBuilder.Append(string.Concat("/nodeReuse:", settings.NodeReuse.Value ? "true" : "false"));
            }
```

Let's use the longer name version to make it easier to understand

2023-07-16 07:25 UTC, augustoproiete commented on src/Cake.Common.Tests/Unit/Tools/DotNet/MSBuild/DotNetMSBuildBuilderTests.cs
> +                Assert.Equal("msbuild /nr:true", result.Args);
```suggestion
                Assert.Equal("msbuild /nodeReuse:true", result.Args);
```

Let's use the longer name version to make it easier to understand

2023-07-16 07:28 UTC, augustoproiete approved these changes
LGTM

2023-08-05 02:05 UTC, alexrp commented
@augustoproiete seems like this one somehow got stuck pending approval despite having approval? 🤔

2023-09-29 15:20 UTC, devlead approved these changes
LGTM 👍

2023-09-29 15:20 UTC, merged

2023-09-29 15:21 UTC, devlead commented
@Marusyk your changes have been merged, thanks for your contribution 👍