Add support for capturing MSBuild properties, items and target results
cake-build/cake pull request #4329
Opened 2024-08-30 19:08 UTC by paulomorgado

Add support for capturing MSBuild properties, items and target results using [Evaluate items and properties and display results of targets](https://learn.microsoft.com/en-us/visualstudio/msbuild/evaluate-items-and-properties).

- Added `StandardOutputAction` properties to `DotNetCoreMSBuildBuilderFixture` and `MSBuildRunnerFixture`.
- Updated `RunTool` methods to pass `StandardOutputAction` to `Build` and `Run` methods.
- Added new test cases in `DotNetMSBuildBuilderTests` and `MSBuildRunnerTests` to verify functionality.
- Added overloads in `DotNetAliases` and `MSBuildAliases` to accept `standardOutputAction` parameter.
- Updated `DotNetMSBuildBuilder` and `MSBuildRunner` to handle `standardOutputAction` and configure process settings.
- Enhanced `MSBuildArgumentBuilderExtensions` to append MSBuild arguments for properties, items, and target results.
- Extended `DotNetMSBuildSettings` and `MSBuildSettings` with new properties and collections.
- Added extension methods in `DotNetMSBuildSettingsExtensions` for fluent configuration.

2024-10-22 18:29 UTC, paulomorgado commented
@devlead, is there anything needed here?

2024-10-30 10:18 UTC, devlead commented
> @devlead, is there anything needed here?

Don't know, a the moment just the maintainers' time to get bearings on what's trying to be achieved and review and understand the multiple changes introduced. Meanwhile, answers to most questions about what's expected from PRs and what to expect can be found in our [Contribution Guidelines](https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md#contribution-guidelines).

2025-01-06 15:17 UTC, devlead requested changes
There’s a lot going on in this pull request, could you add integration tests below for the new bits introduced in this PR
https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake

2025-01-06 19:51 UTC, paulomorgado commented
> There’s a lot going on in this pull request, could you add integration tests below for the new bits introduced in this PR https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake

Done, @devlead!

Please, check if it's enough. I don't want the tests to become too brittle.

2025-01-12 16:45 UTC, devlead requested changes
Found a typo in  the integration tests, also as it's json in a given format wondering if helpers / overload for that should be provided for this to be more useful🤔

2025-01-12 16:45 UTC, devlead commented on tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
> +    Assert.Equal(result.Last(), "}");
```suggestion
    System.Text.Json.JsonDocument result = null;

    // When
    DotNetMSBuild(project.FullPath, settings, output => result = System.Text.Json.JsonDocument.Parse(output.SelectMany(x => x).ToArray()));

    // Then
    Assert.NotNull(result);
    Assert.Equal("1.0.0", result.RootElement.GetProperty("Properties").GetProperty("Version").GetString());
    Assert.Equal("net9.0", result.RootElement.GetProperty("Properties").GetProperty("TargetFramework").GetString());
    Assert.Equal(1, result.RootElement.GetProperty("Items").GetProperty("ProjectReference").GetArrayLength());
    Assert.Equal("Success", result.RootElement.GetProperty("TargetResults").GetProperty("Build").GetProperty("Result").GetString());
    Assert.Equal("Success", result.RootElement.GetProperty("TargetResults").GetProperty("Compile").GetProperty("Result").GetString());
```

2025-01-12 22:51 UTC, paulomorgado commented
> Found a typo in the integration tests, also as it's json in a given format wondering if helpers / overload for that should be provided for this to be more useful🤔

The output can be a string if requesting the value of only one property or JSON for any other cases.

The interpretation of the output is very tied to what the user wants to retrieve and this change does not limit the collection of the output to querying properties, items or results.

I would defer creating any helpers for when the community asks and makes a good case for them.

2025-01-13 06:49 UTC, devlead approved these changes
LGTM

2025-01-13 06:52 UTC, merged

2025-01-13 06:57 UTC, devlead commented
@paulomorgado your changes have been merged, thanks for your contribution 👍