Adds two missing parameters for SignTool
cake-build/cake pull request #4406
Opened 2024-12-04 23:00 UTC by tstewart65

\csp - Cryptographic Service Provider
\kc - Private Key Container Name

Fix for #4404

2024-12-05 08:24 UTC, augustoproiete approved these changes
LGTM

2024-12-05 13:36 UTC, devlead requested changes
LGTM, could you please add som tests in
https://github.com/cake-build/cake/blob/124704e625c670d7469fd9fba1b86596f2883a5c/src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs#L15

2024-12-06 01:42 UTC, tstewart65 commented
I have added the tests for the two new parameters.  I also moved the two new parameters to just before the target assemblies.  That way they are at the end of all the parameters that were already there.

2024-12-07 08:12 UTC, Marusyk approved these changes

2025-01-02 18:02 UTC, merged

2025-01-02 18:03 UTC, devlead commented
@tstewart65 your changes have been merged, thanks for your contribution 👍