Fix detection of current GitHub pull request in Azure Pipelines (#4410)
cake-build/cake pull request #4411
Opened 2024-12-20 13:31 UTC by ap0llo

Fix detection of GitHub Pull Request builds in Azure Pipelines.  
This fixes the issue described in #4410.

To fix the issue, use a `long` instead of an `int` to store the current Pull Request id (read from the Azure Pipelines variable `SYSTEM_PULLREQUEST_PULLREQUESTID`).

I am aware that is a breaking change that might break all code that accesses `AzurePipelinesPullRequestInfo.Id` - however I am not aware of any other way to potentially fix this,

2025-01-02 19:07 UTC, devlead requested changes

2025-01-02 19:07 UTC, devlead commented on src/Cake.Common/Build/AzurePipelines/Data/AzurePipelinesPullRequestInfo.cs
> +        public long Id => GetEnvironmentLongInteger("SYSTEM_PULLREQUEST_PULLREQUESTID");
We're not keen on a breaking change and a major new version, so non-breaking suggestion  is to add a new property, obsolete the current with message and no error, and we'll take the breaking change next major version. Not the prettiest but the least disruptive.

```suggestion
        [Obsolete("Type will change in next major version to long, meanwhile use LongId to ensure proper value returned.")]
        public int Id => GetEnvironmentInteger("SYSTEM_PULLREQUEST_PULLREQUESTID");
        
        /// <summary>
        /// Gets the ID of the pull request that caused this build.
        /// This value is set only if the build ran because of a Git PR affected by a branch policy.
        /// </summary>
        /// <value>
        ///   The ID of the pull request that caused this build.
        /// </value>
        public long LongId => GetEnvironmentLongInteger("SYSTEM_PULLREQUEST_PULLREQUESTID");
```
and 
``` diff
-        public bool IsPullRequest => Id > 0;
+         public bool IsPullRequest => LongId > 0;
```

2025-01-03 11:12 UTC, ap0llo commented on src/Cake.Common/Build/AzurePipelines/Data/AzurePipelinesPullRequestInfo.cs
> +        public long Id => GetEnvironmentLongInteger("SYSTEM_PULLREQUEST_PULLREQUESTID");
Good point, I didn't think of that possibility.

I've adapted the code to match your suggestion

2025-01-04 19:26 UTC, devlead approved these changes
LGTM 👍

2025-01-04 19:50 UTC, merged

2025-01-04 19:50 UTC, devlead commented
@ap0llo your changes have been merged, thanks for your contribution 👍